In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [20]:
candidates_file = "Resources/midterm_election_candidates_2018_0921.csv"
candidates_df = pd.read_csv(candidates_file)
candidates_df.head()

,fec_candidate_id,name,party,status,address_one,address_two,city,state,zip,fec_committee_id,cycle,cand_status,office_state,district,branch,clean_name,url,crp_id,google_entity_id
0,H8AK00140,"GALVIN, ALYSE",IND,C,P.O. BOX 90020,NaN,ANCHORAGE,AK,99509.0,C00665711,2018,C,AK,0,H,Alyse Galvin,https://www.alyse4alaska.com/,NaN,NaN
1,H6AK00045,"YOUNG, DONALD E",REP,I,2504 FAIR BANKS ST,NaN,ANCHORAGE,AK,99503.0,C00012229,2018,C,AK,0,H,Don Young,http://alaskansfordonyoung.com/,N00007999,/m/024p1k
2,H4AL01123,"BYRNE, BRADLEY ROBERTS",REP,I,22489 SEA CLIFF DRIVE,NaN,FAIRHOPE,AL,36532.0,C00545673,2018,C,AL,1,H,Bradley Byrne,https://www.byrneforcongress.com/,N00035380,/m/09g6kty
3,H8AL01066,"KENNEDY, ROBERT JR.",DEM,C,312-T SCHILLINGER RD #116,NaN,MOBILE,AL,36608.0,C00667949,2018,C,AL,1,H,Robert Kennedy,http://www.kennedy4alabama.org/,NaN,NaN
4,H8AL02197,"ISNER, TABITHA KAY",DEM,C,4349 WHITE ACRES RD.,NaN,MONTGOMERY,AL,36106.0,C00657437,2018,C,AL,2,H,Tabitha Isner,http://tabithaisner.com/,NaN,NaN

In [21]:
House_candidates = candidates_df[candidates_df["branch"]=='H']
House_candidates.head()

,fec_candidate_id,name,party,status,address_one,address_two,city,state,zip,fec_committee_id,cycle,cand_status,office_state,district,branch,clean_name,url,crp_id,google_entity_id
0,H8AK00140,"GALVIN, ALYSE",IND,C,P.O. BOX 90020,NaN,ANCHORAGE,AK,99509.0,C00665711,2018,C,AK,0,H,Alyse Galvin,https://www.alyse4alaska.com/,NaN,NaN
1,H6AK00045,"YOUNG, DONALD E",REP,I,2504 FAIR BANKS ST,NaN,ANCHORAGE,AK,99503.0,C00012229,2018,C,AK,0,H,Don Young,http://alaskansfordonyoung.com/,N00007999,/m/024p1k
2,H4AL01123,"BYRNE, BRADLEY ROBERTS",REP,I,22489 SEA CLIFF DRIVE,NaN,FAIRHOPE,AL,36532.0,C00545673,2018,C,AL,1,H,Bradley Byrne,https://www.byrneforcongress.com/,N00035380,/m/09g6kty
3,H8AL01066,"KENNEDY, ROBERT JR.",DEM,C,312-T SCHILLINGER RD #116,NaN,MOBILE,AL,36608.0,C00667949,2018,C,AL,1,H,Robert Kennedy,http://www.kennedy4alabama.org/,NaN,NaN
4,H8AL02197,"ISNER, TABITHA KAY",DEM,C,4349 WHITE ACRES RD.,NaN,MONTGOMERY,AL,36106.0,C00657437,2018,C,AL,2,H,Tabitha Isner,http://tabithaisner.com/,NaN,NaN

In [4]:
cand_financials_file = "Resources/candidate_summary_2018.csv"
cand_financials_df = pd.read_csv(cand_financials_file)
cand_financials_df.head()

,Link_Image,Cand_Name,Cand_Id,Cand_Office,Cand_Office_St,Cand_Office_Dist,Cand_Party_Affiliation,Cand_Incumbent_Challenger_Open_Seat,Total_Receipt,Total_Disbursement,...,Individual_Refund,Party_Committee_Refund,Other_Committee_Refund,Total_Contribution_Refund,Other_Disbursements,Net_Contribution,Net_Operating_Expenditure,Cash_On_Hand_BOP,Debt_Owe_To_Committee,Coverage_Start_Date
0,http://www.fec.gov/fecviewer/CandidateCommitte...,"ASHBY, KEN",H8TX05052,H,TX,4.0,LIB,CHALLENGER,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,NaN
1,http://www.fec.gov/fecviewer/CandidateCommitte...,"ECKHART, DON ELIJAH",S6OH00288,S,OH,0.0,REP,CHALLENGER,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,NaN
2,http://www.fec.gov/fecviewer/CandidateCommitte...,"ZIESING, MICHAEL VINCENT",S8CA00499,S,CA,0.0,GRE,CHALLENGER,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,NaN
3,http://www.fec.gov/fecviewer/CandidateCommitte...,"CUMMINGS, ELIJAH E",H6MD07160,H,MD,7.0,DEM,INCUMBENT,944365.35,1051584.48,...,0.0,0.0,0.0,0.0,444374.9,939333.5,603299.58,954952.82,0.0,01/01/2017
4,http://www.fec.gov/fecviewer/CandidateCommitte...,"SMITH, DOUGLAS MARK MR. JR.",H6MI03172,H,MI,3.0,IND,CHALLENGER,0.00,3873.60,...,0.0,0.0,0.0,0.0,0.0,0.0,3873.60,3873.60,0.0,01/01/2017

In [26]:
#create new table with selected values from cand_financials table. Then, filter it by House and Senate 

cand_financials_cols = [
 'Cand_Id',
 'Cand_Office',
 'Total_Receipt',
 'Total_Disbursement',
 'Cash_On_Hand_COP',
 'Debt_Owed_By_Committee',
 'Coverage_End_Date',
 'Individual_Itemized_Contribution',
 'Individual_Unitemized_Contribution',
 'Individual_Contribution',
 'Other_Committee_Contribution',
 'Party_Committee_Contribution',
 'Cand_Contribution',
 'Total_Contribution',
 'Transfer_From_Other_Auth_Committee',
 'Cand_Loan',
 'Other_Loan',
 'Total_Loan',
 'Offsets_To_Operating_Expenditure',
 'Offsets_To_Fundraising',
 'Offsets_To_Leagal_Accounting',
 'Other_Receipts',
 'Operating_Expenditure',
 'Exempt_Legal_Accounting_Disbursement',
 'Fundraising_Disbursement',
 'Transfer_To_Other_Auth_Committee',
 'Cand_Loan_Repayment',
 'Other_Loan_Repayment',
 'Total_Loan_Repayment',
 'Individual_Refund',
 'Party_Committee_Refund',
 'Other_Committee_Refund',
 'Total_Contribution_Refund',
 'Other_Disbursements',
 'Net_Contribution',
 'Net_Operating_Expenditure',
 'Cash_On_Hand_BOP',
 'Debt_Owe_To_Committee',
 'Coverage_Start_Date']

cand_financials_2 = cand_financials_df[cand_financials_cols].copy()
cand_financials_2.head()

,Cand_Id,Cand_Office,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Coverage_End_Date,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,...,Individual_Refund,Party_Committee_Refund,Other_Committee_Refund,Total_Contribution_Refund,Other_Disbursements,Net_Contribution,Net_Operating_Expenditure,Cash_On_Hand_BOP,Debt_Owe_To_Committee,Coverage_Start_Date
0,H8TX05052,H,0.00,0.00,0.00,0.0,NaN,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,NaN
1,S6OH00288,S,0.00,0.00,0.00,0.0,NaN,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,NaN
2,S8CA00499,S,0.00,0.00,0.00,0.0,NaN,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,NaN
3,H6MD07160,H,944365.35,1051584.48,847733.69,0.0,10/17/2018,310388.35,81946.15,392334.5,...,0.0,0.0,0.0,0.0,444374.9,939333.5,603299.58,954952.82,0.0,01/01/2017
4,H6MI03172,H,0.00,3873.60,0.00,0.0,09/30/2018,0.00,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3873.60,3873.60,0.0,01/01/2017

In [27]:
House_cand_financials = cand_financials_2[cand_financials_2["Cand_Office"]=='H']
House_cand_financials.head()

,Cand_Id,Cand_Office,Total_Receipt,Total_Disbursement,Cash_On_Hand_COP,Debt_Owed_By_Committee,Coverage_End_Date,Individual_Itemized_Contribution,Individual_Unitemized_Contribution,Individual_Contribution,...,Individual_Refund,Party_Committee_Refund,Other_Committee_Refund,Total_Contribution_Refund,Other_Disbursements,Net_Contribution,Net_Operating_Expenditure,Cash_On_Hand_BOP,Debt_Owe_To_Committee,Coverage_Start_Date
0,H8TX05052,H,0.00,0.00,0.00,0.0,NaN,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,NaN
3,H6MD07160,H,944365.35,1051584.48,847733.69,0.0,10/17/2018,310388.35,81946.15,392334.50,...,0.0,0.0,0.0,0.0,444374.9,939333.50,603299.58,954952.82,0.0,01/01/2017
4,H6MI03172,H,0.00,3873.60,0.00,0.0,09/30/2018,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,3873.60,3873.60,0.0,01/01/2017
5,H8FL05140,H,450694.05,447395.51,3298.54,0.0,09/30/2018,384423.00,22743.28,407166.28,...,14952.0,0.0,0.0,14952.0,0.0,435668.63,432370.09,0.00,0.0,01/01/2018
6,H4CA42078,H,0.00,0.00,0.00,0.0,NaN,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,NaN

In [8]:
list(cand_financials_df.columns.values)

['Link_Image',
 'Cand_Name',
 'Cand_Id',
 'Cand_Office',
 'Cand_Office_St',
 'Cand_Office_Dist',
 'Cand_Party_Affiliation',
 'Cand_Incumbent_Challenger_Open_Seat',
 'Total_Receipt',
 'Total_Disbursement',
 'Cash_On_Hand_COP',
 'Debt_Owed_By_Committee',
 'Coverage_End_Date',
 'Cand_Street_1',
 'Cand_Street_2',
 'Cand_City',
 'Cand_State',
 'Cand_Zip',
 'Individual_Itemized_Contribution',
 'Individual_Unitemized_Contribution',
 'Individual_Contribution',
 'Other_Committee_Contribution',
 'Party_Committee_Contribution',
 'Cand_Contribution',
 'Total_Contribution',
 'Transfer_From_Other_Auth_Committee',
 'Cand_Loan',
 'Other_Loan',
 'Total_Loan',
 'Offsets_To_Operating_Expenditure',
 'Offsets_To_Fundraising',
 'Offsets_To_Leagal_Accounting',
 'Other_Receipts',
 'Operating_Expenditure',
 'Exempt_Legal_Accounting_Disbursement',
 'Fundraising_Disbursement',
 'Transfer_To_Other_Auth_Committee',
 'Cand_Loan_Repayment',
 'Other_Loan_Repayment',
 'Total_Loan_Repayment',
 'Individual_Refund',
 'Party_Committee_Refund',
 'Other_Committee_Refund',
 'Total_Contribution_Refund',
 'Other_Disbursements',
 'Net_Contribution',
 'Net_Operating_Expenditure',
 'Cash_On_Hand_BOP',
 'Debt_Owe_To_Committee',
 'Coverage_Start_Date']

In [28]:
#Duplicate Candidates table and filter by house 

candidates_cols = ["fec_candidate_id", "name", "party", "status", "address_one","address_two", "city", "state", "zip",
                  "fec_committee_id", "cycle", ]
premise_transformed= premise_df[premise_cols].copy()

NameError: name 'premise_df' is not defined